### ISSUE TITLE
Incompatible with 1.16.5

### ISSUE THREAD

**Issue by NighthowlerStudios** [plex1on/Infection#3]

**Comment by katelyynn** [comment]
hmm yeah, the datapack doesn't seem to be working as intended on 1.16. do you have any reason to still be on 1.16?

**Comment by katelyynn** [comment]
should be fixed in the next release! (2022.0926)

**Comment by NighthowlerStudios** [comment]
> hmm yeah, the datapack doesn't seem to be working as intended on 1.16. do you have any reason to still be on 1.16?

I wanted to use the pack alongside my gun mod as testing for its functionality.  Plans sorta fell flat but I might try again at some point.

**Comment by katelyynn** [comment]
oh, well the datapack should work as intended in 1.16 now
